### ISSUE TITLE
Process more than one gaitcycle

### ISSUE THREAD

**Issue by BergenGaitLab** [jjnurminen/gaitutils#2]
Hello Jussi.
When we use your scripts to process a trial it cuts the trial before we have foot off identified on the forceplate. It processes a full gait cycle, but not foot off on the forceplate, which we need for the kinetics. It is only on the left side we have a problem. Foot length is added in subject measurements. Can we somehow make the region of interest longer ..?

**Comment by jjnurminen** [comment]
Hi Bergen!

Events are marked according to the `events_range` config option, which should be set according to your lab coordinate system. The easiest way to change it is to go to File/Options, click on the Autoprocessing tab, and change the option that says "Coordinate range for events". For example, if you want to mark events whenever the subject is from -2.5 m to 2.5 m from the coordinate system origin, set the range as `[-2500, 2500]`

The change is applied until the menu is restarted. If you want to apply the change permanently, click on Save... in the options dialog, and save into your home directory as `.gaitutils.cfg`.

If this does not help, let me know.

**Comment by BergenGaitLab** [comment]
Hi Jussi.
Thank you for quick response.
We will try that : )
